version: "3.4"

services:
  Gene.API:
    image: ${DOCKER_REGISTRY-}gene
    build:
      context: .
      dockerfile: Services/Gene/Gene.API/Dockerfile

  MolDb.API:
    image: ${DOCKER_REGISTRY-}moldb
    build:
      context: .
      dockerfile: Services/Chem/MolDb.API/Dockerfile
