version: "3.4"

services:
  Gene.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      # - "KafkaProducerSettings:BootstrapServers=localhost:9092"
      - "KafkaProducerSettings:Topic=genes"

      - "GeneMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "GeneMongoDbSettings:DatabaseName=Gene"
      - "GeneMongoDbSettings:GeneCollectionName=Genes"
      - "GeneMongoDbSettings:GeneRevisionCollectionName=GenesRevisions"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      # - "KafkaConsumerSettings:BootstrapServers=localhost:9092"
      - "KafkaConsumerSettings:Topic=genes"
      - "KafkaConsumerSettings:GroupId=gene-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

    ports:
      - "8001:80"

  MolDb.API:
    ports:
      - "8101:80"
