version: "3.4"

services:
  Gene.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "GeneMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "GeneMongoDbSettings:DatabaseName=Gene"

      - "GeneMongoDbSettings:GeneCollectionName=Genes"
      - "GeneMongoDbSettings:StrainCollectionName=Strains"
      - "GeneMongoDbSettings:GeneEssentialityCollectionName=Essentialities"
      - "GeneMongoDbSettings:GeneProteinProductionCollectionName=ProteinProductions"
      - "GeneMongoDbSettings:GeneProteinActivityAssayCollectionName=ProteinActivityAssays"
      - "GeneMongoDbSettings:GeneHypomorphCollectionName=Hypomorphs"
      - "GeneMongoDbSettings:GeneCrispriStrainCollectionName=CrispriStrains"
      - "GeneMongoDbSettings:GeneResistanceMutationCollectionName=ResistanceMutations"
      - "GeneMongoDbSettings:GeneVulnerabilityCollectionName=Vulnerabilities"
      - "GeneMongoDbSettings:GeneUnpublishedStructuralInformationCollectionName=UnpublishedStructuralInformations"
      
      - "GeneMongoDbSettings:GeneRevisionCollectionName=GenesRevisions"
      - "GeneMongoDbSettings:StrainRevisionCollectionName=StrainsRevisions"
      - "GeneMongoDbSettings:GeneEssentialityRevisionCollectionName=EssentialitiesRevisions"
      - "GeneMongoDbSettings:GeneProteinProductionRevisionCollectionName=ProteinProductionsRevisions"
      - "GeneMongoDbSettings:GeneProteinActivityAssayRevisionCollectionName=ProteinActivityAssaysRevisions"
      - "GeneMongoDbSettings:GeneHypomorphRevisionCollectionName=HypomorphsRevisions"
      - "GeneMongoDbSettings:GeneCrispriStrainRevisionCollectionName=CrispriStrainsRevisions"
      - "GeneMongoDbSettings:GeneResistanceMutationRevisionCollectionName=ResistanceMutationsRevisions"
      - "GeneMongoDbSettings:GeneVulnerabilityRevisionCollectionName=VulnerabilitiesRevisions"
      - "GeneMongoDbSettings:GeneUnpublishedStructuralInformationRevisionCollectionName=UnpublishedStructuralInformationsRevisions"
      
      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=gene-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

    ports:
      - "8001:80"

  Target.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "TargetMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "TargetMongoDbSettings:DatabaseName=Target"

      - "TargetMongoDbSettings:TargetCollectionName=Targets"

      - "TargetMongoDbSettings:TargetRevisionCollectionName=TargetsRevisions"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=target-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

    ports:
      - "8002:80"


  Screen.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "ScreenMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "ScreenMongoDbSettings:DatabaseName=Screen"

      - "ScreenMongoDbSettings:ScreenCollectionName=Screens"
      - "ScreenMongoDbSettings:ScreenRunCollectionName=ScreenRuns"
      - "ScreenMongoDbSettings:HitCollectionCollectionName=HitCollections"
      - "ScreenMongoDbSettings:HitCollectionName=Hits"


      - "ScreenMongoDbSettings:ScreenRevisionCollectionName=ScreensRevisions"
      - "ScreenMongoDbSettings:ScreenRunRevisionCollectionName=ScreenRunsRevisions"
      - "ScreenMongoDbSettings:HitCollectionRevisionCollectionName=HitCollectionsRevisions"
      - "ScreenMongoDbSettings:HitRevisionCollectionName=HitRevisions"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=screen-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      - "MolDbAPI:Url=http://MolDb.API/api/v2"

    ports:
      - "8003:80"

  
  HitAssessment.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "HAMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "HAMongoDbSettings:DatabaseName=HitAssessment"

      - "HAMongoDbSettings:HitAssessmentCollectionName=HitAssessments"
      - "HAMongoDbSettings:HaCompoundEvolutionCollectionName=HaCompoundEvolutions"

      - "HAMongoDbSettings:HitAssessmentRevisionCollectionName=HitAssessmentsRevisions"
      - "HAMongoDbSettings:HaCompoundEvolutionRevisionCollectionName=HaCompoundEvolutionsRevisions"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=hitassessment-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      - "MolDbAPI:Url=http://MolDb.API/api/v2"

    ports:
      - "8004:80"

  Project.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "ProjectMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "ProjectMongoDbSettings:DatabaseName=Project"

      - "ProjectMongoDbSettings:ProjectCollectionName=Projects"
      - "ProjectMongoDbSettings:ProjectCompoundEvolutionCollectionName=ProjectCompoundEvolutions"

      - "ProjectMongoDbSettings:ProjectRevisionCollectionName=ProjectsRevisions"
      - "ProjectMongoDbSettings:ProjectCompoundEvolutionRevisionCollectionName=ProjectCompoundEvolutionsRevisions"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=project-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      - "MolDbAPI:Url=http://MolDb.API/api/v2"

    ports:
      - "8005:80"

  Horizon.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "HorizonNeo4jSettings:Uri=bolt://neo4j:7687"
      - "HorizonNeo4jSettings:User=neo4j"
      - "HorizonNeo4jSettings:Password=1k5SPVHJ4FZ9"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=horizon-gene-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

    ports:
      - "8006:80"

  MolDb.API:
    environment:
      - "KafkaConsumerSettings_BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings_Topics=daikon-core-events"
      - "KafkaConsumerSettings_GroupId=moldb-consumer-group"
      - "KafkaConsumerSettings_AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings_EnableAutoCommit=true"
      - "KafkaConsumerSettings_AllowAutoCreateTopics=true"
    ports:
      - "8101:80"
