version: "3.4"

services:
  Gene.API:
    image: ${DOCKER_REGISTRY-}gene
    build:
      context: .
      dockerfile: Services/Gene/Gene.API/Dockerfile
  
  Horizon.API:
    image: ${DOCKER_REGISTRY-}horizon
    build:
      context: .
      dockerfile: Services/Horizon/Horizon.API/Dockerfile

  MolDb.API:
    image: ${DOCKER_REGISTRY-}moldb
    build:
      context: .
      dockerfile: Services/Chem/MolDb.API/Dockerfile
