version: "3.4"

services:
  MolDb.API:
    image: ${DOCKER_REGISTRY-}moldb
    build:
      context: .
      dockerfile: Services/Chem/MolDb.API/Dockerfile
    environment:
      - "KafkaConsumerSettings_BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings_Topics=daikon-core-events"
      - "KafkaConsumerSettings_GroupId=moldb-consumer-group"
      - "KafkaConsumerSettings_AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings_EnableAutoCommit=true"
      - "KafkaConsumerSettings_AllowAutoCreateTopics=true"
    ports:
      - "8101:80"
